### PR TITLE
Appsync Graphql API and Expo Frontend Setup with Amplify

### PR DESCRIPTION
**Pull request by c3duan**
### Administrative Info
Monday Board ID: 853606148
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Setup Amplify backend with initial Graphql schemas
- Setup Appsync Graphql API
- Add Basic AWS Cognito Authentication
- Setup Expo frontend with Graphql types for Typescript
- Added pre-commit eslint hooks

### Testing
How did you confirm your changes worked? 
- Initial setup

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Amplify Push Success |
| --- |
| Screen Shot 2021-01-19 at 4 23 13 PM |

### CODE REVIEW

**Review by sharmaadvay0 — APPROVED** [review]
Looks Good!

**Review by hanakims — APPROVED** [review]
lgtm!

**Review by bobbytatum27 — APPROVED** [review]
lgtm

**Review by TheHiddenLayer — APPROVED** [review]
good

**Review by thai-truong — APPROVED** [review]
lgtm, I checked most of the non-autogenerated files

**Pull request merged**
