### PR TITLE
Add XML of all badge SVGs to src/assets folder

### PR DESCRIPTION
**Pull request by thai-truong**
### Administrative Info
Monday Board ID: 853606148
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- I added the XML for all currently available badge SVGs on Figma to src/assets.

### Testing
How did you confirm your changes worked? 
- I'm only adding asset files so I didn't think I needed any tests here.

### Confirmation of Change 
Check src/assets. These are only asset files and they are not used anywhere else as of now.

### CODE REVIEW

**Comment by c3duan** [comment]
@thaigillespie We are moving away from SVG XML and are instead rewriting the SVG as a React Functional Component. So later on, we can dynamically change the fill color. An example of what this looks like is in `src/assets/logo.tsx`.

**Review by c3duan — CHANGES_REQUESTED** [review]
@thaigillespie We are moving away from SVG XML and are instead rewriting the SVG as a React Functional Component. So later on, we can dynamically change the fill color. An example of what this looks like is in `src/assets/logo.tsx`.

**Comment by thai-truong** [comment]
I thought we were gonna use this for these XMLs (https://github.com/TritonSE/Your-Clear-Way/blob/main/src/components/SvgContainer.tsx) so that's why I did what I did here. There are lots of badges so it's gonna take a lot of time to do what is done in src/assets/logo.tsx @c3duan

**Comment by c3duan** [comment]
> I thought we were gonna use this for these XMLs (https://github.com/TritonSE/Your-Clear-Way/blob/main/src/components/SvgContainer.tsx) so that's why I did what I did here. There are lots of badges so it's gonna take a lot of time to do what is done in src/assets/logo.tsx @c3duan

This SVG container component is from a previous PR, and we have decided to use the functional component pattern and have not updated it. It is very tedious, and that is why Bobby was considering having a high school intern to do this job 😄

**Comment by thai-truong** [comment]
Ah I see... Maybe it's better to leave a high school intern to do it yeah, I thought we were still using XMLs that's why I did this thinking it wasn't that bad :))

**Comment by thai-truong** [comment]
Welp thanks for letting me know anyway @c3duan. Should I just close this PR then?

**Comment by c3duan** [comment]
> Welp thanks for letting me know anyway @c3duan. Should I just close this PR then?

Honestly, since the XML works fine we can just use what you have right now so we can move faster to complete the pages. I think the only thing we need is to add a string props in the SvgContainer component to map the title to the corresponding xml.

**Comment by thai-truong** [comment]
> 
> 
> > Welp thanks for letting me know anyway @c3duan. Should I just close this PR then?
> 
> Honestly, since the XML works fine we can just use what you have right now so we can move faster to complete the pages. I think the only thing we need is to add a string props in the SvgContainer component to map the title to the corresponding xml.

Yep, I'll do that. Thanks for the help!

**Comment by thai-truong** [comment]
> 
> 
> > > Welp thanks for letting me know anyway @c3duan. Should I just close this PR then?
> > 
> > 
> > Honestly, since the XML works fine we can just use what you have right now so we can move faster to complete the pages. I think the only thing we need is to add a string props in the SvgContainer component to map the title to the corresponding xml.
> 
> Yep, I'll do that. Thanks for the help!

@c3duan On second thoughts, I think it's better to leave SvgContainer as is. This functional component is already taking an xml string as a prop. This means that when I use SvgContainer for the badges, I can just use the question's title to get the needed xml, then pass it down to SvgContainer as a prop whenever I want to render the SVG for badges. This way we can keep SvgContainer as generalized as possible. What do you think?

**Comment by c3duan** [comment]
> > > > Welp thanks for letting me know anyway @c3duan. Should I just close this PR then?
> > > 
> > > 
> > > Honestly, since the XML works fine we can just use what you have right now so we can move faster to complete the pages. I think the only thing we need is to add a string props in the SvgContainer component to map the title to the corresponding xml.
> > 
> > 
> > Yep, I'll do that. Thanks for the help!
> 
> @c3duan On second thoughts, I think it's better to leave SvgContainer as is. This functional component is already taking an xml string as a prop. This means that when I use SvgContainer for the badges, I can just use the question's title to get the needed xml, then pass it down to SvgContainer as a prop whenever I want to render the SVG for badges. This way we can keep SvgContainer as generalized as possible. What do you think?

If we are doing this, there is no point to have the separate SvgContainer component and we can just use the SvgXml component directly. The idea I was thinking of is to use the title of the question as a string props to SvgContainer and SvgContainer will do the mapping for us, so we don't have to import the js object everywhere we need to show the icons. Either way works.

**Comment by thai-truong** [comment]
> 
> 
> > > > > Welp thanks for letting me know anyway @c3duan. Should I just close this PR then?
> > > > 
> > > > 
> > > > Honestly, since the XML works fine we can just use what you have right now so we can move faster to complete the pages. I think the only thing we need is to add a string props in the SvgContainer component to map the title to the corresponding xml.
> > > 
> > > 
> > > Yep, I'll do that. Thanks for the help!
> > 
> > 
> > @c3duan On second thoughts, I think it's better to leave SvgContainer as is. This functional component is already taking an xml string as a prop. This means that when I use SvgContainer for the badges, I can just use the question's title to get the needed xml, then pass it down to SvgContainer as a prop whenever I want to render the SVG for badges. This way we can keep SvgContainer as generalized as possible. What do you think?
> 
> If we are doing this, there is no point to have the separate SvgContainer component and we can just use the SvgXml component directly. The idea I was thinking of is to use the title of the question as a string props to SvgContainer and SvgContainer will do the mapping for us, so we don't have to import the js object everywhere we need to show the icons. Either way works.

That's a good point. I'll do that for now then.

**Review by bobbytatum27 — COMMENTED** [review]
Overall, nice work on the PR! I only have one comment - in your definition of `badgeXMLs`, certain keys are not strings (Dryers, Refrigerator, Compost). Since the object properties are accessed via bracket syntax, we need the keys to be strings. Other than that, thanks for improving the SvgContainer!

**Comment by thai-truong** [comment]
> 
> 
> Overall, nice work on the PR! I only have one comment - in your definition of `badgeXMLs`, certain keys are not strings (Dryers, Refrigerator, Compost). Since the object properties are accessed via bracket syntax, we need the keys to be strings. Other than that, thanks for improving the SvgContainer!

See, funny enough, ESLint actually made those changes, not me. I originally had all the keys as literal strings. Then after I committed the code and commit hooks are run, ESLint changed the keys with short length to just variable-esque words. Regardless, I think that should still work just fine (else I don't think ESLint would change those keys to be like that). 

Here's a small code snippet I wrote to demonstrate that we can still use bracket syntax to access the values for non-string keys (since I think under the hood JS treats those inputted keys as strings anyway): https://jsfiddle.net/02hpuv8r/

Some more MDN links regarding JS objects and on the topic of JS object property access: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_Accessors, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects

Otherwise, we just need to turn off this rule for ESLint. Problem is, I don't know which rule this is, and looking it up online didn't yield any result...

@bobbytatum27

**Comment by bobbytatum27** [comment]
> > Overall, nice work on the PR! I only have one comment - in your definition of `badgeXMLs`, certain keys are not strings (Dryers, Refrigerator, Compost). Since the object properties are accessed via bracket syntax, we need the keys to be strings. Other than that, thanks for improving the SvgContainer!
> 
> See, funny enough, ESLint actually made those changes, not me. I originally had all the keys as literal strings. Then after I committed the code and commit hooks are run, ESLint changed the keys with short length to just variable-esque words. Regardless, I think that should still work just fine (else I don't think ESLint would change those keys to be like that).
> 
> Here's a small code snippet I wrote to demonstrate that we can still use bracket syntax to access the values for non-string keys (since I think under the hood JS treats those inputted keys as strings anyway): https://jsfiddle.net/02hpuv8r/
> 
> Some more MDN links regarding JS objects and on the topic of JS object property access: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_Accessors, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects
> 
> Otherwise, we just need to turn off this rule for ESLint. Problem is, I don't know which rule this is, and looking it up online didn't yield any result...
> 
> @bobbytatum27

Thanks for providing that snippet! It seems I was wrong that object property access would be an issue. Nevertheless, I tried prepending `/*eslint quote-props: ["error", "consistent"]*/` to the file to enforce quote consistency. ESLint did indeed complain when the pre-commit checks ran (error along the lines of _inconsistently quoted property found_), but when I added quotes to the properties causing issues, I received the following errors: _Replace `"Dryers"` with `Dryers` _, etc. From this message, I'm suspecting that quotes are automatically inserted into the property name while being parsed. I couldn't find any other rules from ESLint that might help here, so I'm at a dead end.

Regardless, this seems to be a discussion revolving around ESLint behavior for only three properties, so I think the return on the time investment to fix this is too minimal to justify keeping at it. I'll give this PR an approval right now, great work!

@thaigillespie

**Review by bobbytatum27 — APPROVED** [review]
lgtm

**Review by c3duan — APPROVED** [review]
lgtm, thanks for migrating all the svgs

**Review by kunalb123 — APPROVED** [review]

**Pull request merged**
