### PR TITLE
Repo clean up

### PR DESCRIPTION
**Pull request by c3duan**
### Administrative Info
Monday Board ID: 853606148
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Remove unnecessary files
- Clean up repo

### Testing
How did you confirm your changes worked? 
- N/A

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
N/A

### CODE REVIEW

**Review by shravanhariharan2 — APPROVED** [review]

**Review by sharmaadvay0 — APPROVED** [review]
lgtm

**Comment by shravanhariharan2** [comment]
Is anyone running into issues with `amplify pull` or `amplify push` after this PR was merged? I think deleting the `amplify/team-provider-info.json` file deleted some config needed for amplify to manage environments. I'm specifically running into [this error](url) for `amplify push` that should be fixable by adding back the file (unless that config is different for each person or something like that)

**Comment by c3duan** [comment]
You should have the file locally, just don't push/commit to this public GitHub repository.

**Comment by shravanhariharan2** [comment]
I have the file locally, but its completely blank. I'll just copy what was on the file in before this PR and see if it works

**Pull request merged**
