### PR TITLE
Fix Lambda function date inconsistencies + update config to support env vars

### PR DESCRIPTION
**Pull request by shravanhariharan2**
### Administrative Info
Monday Board ID: 853606148
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Fixed questions list lambda function dates to match the date types generated by Amplify (see [here](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html) for types)
- Updated config to dynamically change the table name based on environment (dev vs prod)

### Testing
How did you confirm your changes worked? 
- Questions list written successfully to DynamoDB

### Confirmation of Change 
`updatedAt` (and `createdAt`) have different and proper types now:
image

### CODE REVIEW

**Review by c3duan — APPROVED** [review]
LGTM! @shravanhariharan2 Thanks for putting out the changes so fast! Can you do me one favor to make sure the Cognito trigger works as expected: create a new user from the mobile sign-up UI and see if that new user is added to the DynamoDB table? It is hard to write integration tests for lambda functions. Since our backend is quite simple, manual tests is the way for now 😆

**Comment by c3duan** [comment]
nit: @shravanhariharan2  Do we still need `dotenv`? (don't think we need `.env` anymore)  If not we can remove it from `package.json`.

**Comment by bobbytatum27** [comment]
> LGTM! @shravanhariharan2 Thanks for putting out the changes so fast! Can you do me one favor to make sure the Cognito trigger works as expected: create a new user from the mobile sign-up UI and see if that new user is added to the DynamoDB table? It is hard to write integration tests for lambda functions. Since our backend is quite simple, manual tests is the way for now 😆

Just made a user using sign-up UI from this branch. It appears the user (PRTestUser1) was added to the table in DynamoDB (4th row). Here's a screenshot to show 😁:

Screen Shot 2021-05-06 at 9 34 50 PM

**Review by bobbytatum27 — APPROVED** [review]
LGTM! Great work!

**Comment by shravanhariharan2** [comment]
@c3duan you are correct, we don't need `dotenv`, `.env.example`, and `.env`. I'll go ahead and remove those

**Comment by sharmaadvay0** [comment]
I'm not sure if it has to do with this PR but i'm getting this warning now:

Screen Shot 2021-05-07 at 11 11 03 AM

**Comment by shravanhariharan2** [comment]
@sharmaadvay0 I'm unable to replicate that on `main`, sign up / confirmation / login seems to work fine for me. Where in the auth flow is the warning coming up?

**Comment by sharmaadvay0** [comment]
> @sharmaadvay0 I'm unable to replicate that on `main`, sign up / confirmation / login seems to work fine for me. Where in the auth flow is the warning coming up?

It's as soon as I open the app (probably after the auto-login)

**Review by sharmaadvay0 — APPROVED** [review]
LGTM! It looks like you will have to rebase this PR with main now.

**Pull request merged**
